### ISSUE TITLE
[vitest Angular] Watch mode broken

### ISSUE THREAD

**Issue by R-Bower** [analogjs/analog#1501]
### Please provide the environment you discovered this bug in.

```json
"@analogjs/platform": "~1.10.2-beta.11",
"@analogjs/vite-plugin-angular": "~1.10.2-beta.11",
"@analogjs/vitest-angular": "~1.10.2-beta.11",
```

### Which area/package is the issue in?

vitest-angular

### Description

Tests do not update in watch mode.  vitest looks like it's reloading, but new test blocks aren't picked up, nor are changes to existing tests.

### Other information

reproduction: https://github.com/R-Bower/analog-vitest-watch-issue

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Fix released in [v1.10.2-beta.12](https://github.com/analogjs/analog/releases/tag/v1.10.2-beta.12)

**Comment by R-Bower** [comment]
@brandonroberts did you test this change? I have upgraded but the bug is still there.
