### ISSUE TITLE
An unhandled exception occurred: Cannot find module '@nx/devkit' When adding vitest to angular 19

### ISSUE THREAD

**Issue by Oussemasahbeni** [analogjs/analog#1527]
### Please provide the environment you discovered this bug in.

"dependencies": {
    "@angular/animations": "19.0.1",
    "@angular/cdk": "19.0.1",
    "@angular/common": "19.0.1",
    "@angular/compiler": "19.0.1",
    "@angular/core": "19.0.1",
    "@angular/forms": "19.0.1",
    "@angular/material": "19.0.1",
    "@angular/material-luxon-adapter": "19.0.1",
    "@angular/platform-browser": "19.0.1",
    "@angular/platform-browser-dynamic": "19.0.1",
    "@angular/router": "19.0.1",
    "@angular/service-worker": "19.0.1",
    "@angular/youtube-player": "^19.0.1",
    "@botom/quill-resize-module": "^2.0.1",
    "@iplab/ngx-file-upload": "^19.0.1",
    "@jsverse/transloco": "^7.5.0",
    "@ngneat/overview": "^6.0.0",
    "@ngxpert/hot-toast": "^4.1.0 ",
    "angular-code-input": "^2.0.0",
    "aos": "^2.3.4",
    "crypto-js": "4.2.0",
    "date-fns": "^4.1.0",
    "emoji-picker-element": "^1.23.0",
    "lodash-es": "4.17.21",
    "luxon": "3.4.4",
    "net": "^1.0.2",
    "ng-recaptcha": "^13.2.1",
    "ngx-gauge": "^10.0.0",
    "ngx-image-cropper": "^7.2.1",
    "ngx-infinite-scroll": "^19.0.0",
    "ngx-papaparse": "^8.0.0",
    "ngx-quill": "^27.0.0",
    "ngx-sharebuttons": "15.0.6",
    "perfect-scrollbar": "1.5.5",
    "quill": "^2.0.2",
    "rxjs": "7.8.1",
    "sockjs-client": "^1.6.1",
    "stompjs": "^2.3.3",
    "tslib": "2.6.2",
    "zone.js": "0.15.0"
  },
  "devDependencies": {
    "@analogjs/platform": "^1.10.3",
    "@angular-devkit/build-angular": "^19.0.2",
    "@angular/build": "^19.0.2",
    "@angular/cli": "19.0.2",
    "@angular/compiler-cli": "19.0.1",
    "@commitlint/cli": "^19.5.0",
    "@commitlint/config-conventional": "^19.5.0",
    "@commitlint/cz-commitlint": "^19.5.0",
    "@ngx-env/builder": "^19.0.2",
    "@playwright/test": "1.49.1",
    "@smarttools/eslint-plugin-rxjs": "^1.0.8",
    "@tailwindcss/typography": "0.5.13",
    "@types/aos": "^3.0.7",
    "@types/chroma-js": "2.4.4",
    "@types/crypto-js": "4.2.2",
    "@types/highlight.js": "10.1.0",
    "@types/jasmine": "5.1.4",
    "@types/lodash": "4.17.4",
    "@types/lodash-es": "4.17.12",
    "@types/luxon": "3.4.2",
    "@types/sockjs-client": "^1.5.4",
    "@types/stompjs": "^2.3.9",
    "@typescript-eslint/parser": "^8.18.1",
    "angular-eslint": "19.0.2",
    "autoprefixer": "10.4.19",
    "chroma-js": "2.4.2",
    "commitizen": "^4.3.1",
    "cross-env": "^7.0.3",
    "cz-conventional-changelog": "^3.3.0",
    "eslint": "^9.9.1",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-playwright": "^2.1.0",
    "eslint-plugin-prettier": "^5.2.1",
    "husky": "^8.0.0",
    "inquirer": "^9.3.7",
    "jasmine-core": "5.1.2",
    "karma": "6.4.3",
    "karma-chrome-launcher": "3.2.0",
    "karma-coverage": "2.2.1",
    "karma-jasmine": "5.1.0",
    "karma-jasmine-html-reporter": "2.1.0",
    "lint-staged": "^15.2.10",
    "lodash": "4.17.21",
    "playwright-ng-schematics": "^1.2.2",
    "postcss": "8.4.38",
    "prettier": "^3.3.0",
    "prettier-eslint": "^16.3.0",
    "prettier-plugin-organize-imports": "3.2.4",
    "prettier-plugin-tailwindcss": "0.6.1",
    "source-map-explorer": "^2.5.3",
    "tailwindcss": "3.4.3",
    "typescript": "5.5.3",
    "typescript-eslint": "8.17.0"
  }

### Which area/package is the issue in?

vitest-angular

### Description

I was trying to add vitest to an angular 19 app, the only step that i did is
`npm i @analogjs/platform -D` then when i type in the command 

`ng g @analogjs/platform:setup-vitest --project my-vitest-app` i got the error of   Cannot find module '@nx/devkit'

### Please provide the exception or error you saw

```true
sahba@OussemaSahbeni MINGW64 ~/OneDrive/Desktop/inspark/onesaha/onesaha-frontend (feature/newsletter)
$ ng g @analogjs/platform:setup-vitest --project onesaha-frontend
An unhandled exception occurred: Cannot find module '@nx/devkit'
Require stack:
- C:\Users\sahba\OneDrive\Desktop\inspark\onesaha\onesaha-frontend\node_modules\@analogjs\platform\src\lib\nx-plugin\src\generators\setup-vitest\compat.js
- C:\Users\sahba\OneDrive\Desktop\inspark\onesaha\onesaha-frontend\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\sahba\OneDrive\Desktop\inspark\onesaha\onesaha-frontend\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\sahba\OneDrive\Desktop\inspark\onesaha\onesaha-frontend\node_modules\@angular\cli\src\command-builder\schematics-command-module.js
- C:\Users\sahba\OneDrive\Desktop\inspark\onesaha\onesaha-frontend\node_modules\@angular\cli\src\commands\generate\cli.js
- C:\Users\sahba\OneDrive\Desktop\inspark\onesaha\onesaha-frontend\node_modules\@angular\cli\src\commands\command-config.js
- C:\Users\sahba\OneDrive\Desktop\inspark\onesaha\onesaha-frontend\node_modules\@angular\cli\src\command-builder\command-runner.js
- C:\Users\sahba\OneDrive\Desktop\inspark\onesaha\onesaha-frontend\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\sahba\AppData\Roaming\nvm\v22.11.0\node_modules\@angular\cli\lib\init.js
See "C:\Users\sahba\AppData\Local\Temp\ng-KJ4Otc\angular-errors.log" for further details.
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Resolved on Discord, the peer dependencies weren't installed.

```sh
npm install @analogjs/platform --legacy-peer-deps
```

Install manually

```sh
npm install @analogjs/platform @nx/vite @nx/angular @nx/devkit --save-dev
```

**Comment by MikeDabrowski** [comment]
still happening. I first installed @nx/devkit then followed the docs
