### ISSUE TITLE
Support liveReload with rolldown-vite@7.2.x

### ISSUE THREAD

**Issue by benpsnyder** [analogjs/analog#1714]
### Which scope/s are relevant/related to the feature request?

create-analog

### Information

With this I can get the `serve` to work
```sh
analog({
...
        // liveReload: false,
...
)}
```

With this I cannot get `serve` to function
```sh
analog({
...
        liveReload: true,
...
)}
```

I have provided @brandonroberts with repo access to a branch specific to this issue

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [x] No

**Comment by brandonroberts** [comment]
Closing as resolved in the latest beta `1.18.0-beta.3`

**Comment by benpsnyder** [comment]
Still not working for me on our internal repo for SSR and CSR apps. I will open another issue once I get more time to put in more work myself.

**Comment by benpsnyder** [comment]
@brandonroberts the PR on our internal repo labeled `feat(meritOS): upgrade to rolldown-vite with experimental enableNativePlugin true on portal but not adastra` is ready! You'll find `liveReload: false` on both apps. I listed out some findings on the PR.

**Comment by benpsnyder** [comment]
I will be updating https://github.com/benpsnyder/analog/tree/feat/liveReload-true-tailwind4-prefix with a reproducible repo. We will do:
- **an SSR app using postcss** -- `pnpm exec nx generate @analogjs/platform:application --analogAppName=ssrwithpostcsstw --addTailwind=true --no-interactive`
- **an SSR app using the TW4 plugin, without postcss** -- `pnpm exec nx generate @analogjs/platform:application --analogAppName=ssrwithplugintw --addTailwind=true --no-interactive`
- **a CSR app using postcss** -- `pnpm exec nx generate @analogjs/platform:application --analogAppName=csrwithpostcsstw --addTailwind=true --no-interactive`
- **a CSR app using the TW4 plugin, without postcss** -- `pnpm exec nx generate @analogjs/platform:application --analogAppName=csrwithplugintw --addTailwind=true --no-interactive`

**Comment by brandonroberts** [comment]
Live reload is confirmed as working with Analog 2.x and rolldown-vite 7.2.x. The Tailwind configuration needing updating is a separate issue.
