### ISSUE TITLE
SCSS from Angular libraries not preprocessed when building Storybook with Vite

### ISSUE THREAD

**Issue by spawnrider** [analogjs/analog#2018]
### Please provide the environment you discovered this bug in.

Node : v22.15.1
Angular :  
- "@angular/cli": "^21.0.3"
- "@angular/common": "^21.0.5",
Angular AnalogJS : 
- "@analogjs/storybook-angular": "^2.2.0"

Here is my main.ts configuration : 
```
import type { StorybookConfig } from '@analogjs/storybook-angular';
import { UserConfig, mergeConfig } from 'vite';
import viteTsConfigPaths from 'vite-tsconfig-paths';

const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: ['@storybook/addon-docs', '@storybook/addon-designs', '@storybook/addon-a11y'],
  framework: {
    name: '@analogjs/storybook-angular',
    options: {},
  },
  staticDirs: ['../src/shared/assets', './assets'],

  async viteFinal(config: UserConfig) {
    return mergeConfig(config, {
      plugins: [viteTsConfigPaths()],
    });
  },
};

export default config;
```

The angular.json part relative to build-storybook : 
```
        "build-storybook": {
          "builder": "@analogjs/storybook-angular:build-storybook",
          "options": {
            "configDir": ".storybook",
            "experimentalZoneless": true,
            "compodoc": true,
            "compodocArgs": [
              "-e",
              "json",
              "-d",
              "."
            ],
            "outputDir": "storybook-static",
            "stylePreprocessorOptions": {
              "loadPaths": [
                "src/shared/styles",
                "src/components/**/"
              ]
            }
          }
        }
```

### Which area/package is the issue in?

storybook-angular

### Description

I recently switched Storybook’s builder from Webpack to Vite in an Angular component libraries monorepo.

**The setup is:**

- Angular
- Multiple libraries with multiple entry points (ng-packages)
- Storybook builder: Vite

**What works**

When running start-storybook:

- Components render correctly
- Styles are applied correctly
- SCSS is properly processed

**The problem**

When running build-storybook (static build):

- Components still render correctly
- SCSS from Angular components is NOT preprocessed
- Raw SCSS is injected directly into the generated assets
- Variables, nesting and mixins remain uncompiled

**Expected behavior**

SCSS should be processed the same way as:

- start-storybook
- ng build
- Storybook with the Webpack builder

**What I tried**

- Custom Vite css.preprocessorOptions
- Custom Vite plugins
- Storybook viteFinal configuration
- Trying to align with Angular CLI / ng-packagr behavior

None of these changes seem to affect how SCSS from Angular libraries is handled during the static build.

**Question**
Is this a known limitation of Storybook + Vite when used with Angular libraries and ng-packagr (secondary entry points)?
Is there a specific configuration required to ensure SCSS preprocessing is applied during build-storybook?
Any guidance or minimal working example would be appreciated.

### Please provide the exception or error you saw

```true
My angular component is rendered without the right style (if it using SCSS).
```

### Other information

Here is the resultat on my _storybook-static/assets/sr-button.xyz.js_ file : <img width="678" height="625" alt="Image" src="https://github.com/user-attachments/assets/b9b37069-290f-4738-84a1-332391367f3b" />

See the source folders organization : 

<img width="372" height="720" alt="Image" src="https://github.com/user-attachments/assets/31626ae9-b9f8-4692-b6a1-88c543cea0a1" />

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [x] No

**Comment by brandonroberts** [comment]
Thanks @spawnrider. I have a repo here that's working correctly with the static build. Can you reproduce the issue with it?

https://github.com/brandonroberts/angular-vite-storybook/tree/lib-button

**Comment by th0r** [comment]
I experience the same problem - I see uncompiled scss code in the `storybook-static` directory thus the compiled storybook UI shows unstyled components.

**Comment by brandonroberts** [comment]
A small repo showing the issue would help identify the problem

**Comment by th0r** [comment]
Here you are: https://github.com/th0r/ng-analogjs-storybook-angular-styles-bug

Check `npm run storybook` first - you'll see a styled button.
After that run `npm run build-storybook` and the button will be unstyled there.

**Comment by brandonroberts** [comment]
@th0r thanks. Will take a look

**Comment by th0r** [comment]
And another problem I found is that global styles (from `styles` option in `angular.json`) are not resolved correctly if `.storybook` directory is not located in the root of the project, but somewhere else.

In this case `npm run storybook` reports
```
Vite Internal server error: Failed to resolve import
│  "src/stories/styles/global.scss" from "src/.storybook/preview.ts". Does the file
│  exist?
```
and `npm run build-storybook` reports
```
[vite]: Rollup failed to resolve import "src/stories/styles/global.scss" from
│  "./src/.storybook/preview.ts".
```
Using `/src/...` instead of `src/...` doesn't fix the issue either.

I think we should resolve proper import path for each global style like `path.resolve(<location_of_angular_json>, <project_root_from_angular_json>, <global_style_path>)` instead of just taking paths from the config as-is.

I've reproduced the problem in the same repo in the `global-styles-import-problem` branch: https://github.com/th0r/ng-analogjs-storybook-angular-styles-bug/tree/global-styles-import-problem

**Comment by spawnrider** [comment]
Thanks guys for the help. I will take a look at the fix quickly 👍🏽

**Comment by th0r** [comment]
Thanks @brandonroberts for an almost instant fix!

**Comment by brandonroberts** [comment]
Both issues should be resolved in the latest beta `2.2.1-beta.6`. Thanks!

**Comment by th0r** [comment]
Sorry @brandonroberts, but the issue is still there for me.
Updated a reproduction repo with `2.2.1-beta.6` and still can't see styles in the build storybook.

**Comment by brandonroberts** [comment]
@th0r you need to update the `@analogjs/vite-plugin-angular` package to `2.2.1-beta.6`. Or delete the `package-lock.json` and re-install.

<img width="631" height="148" alt="Image" src="https://github.com/user-attachments/assets/3cb162ee-656e-4322-9797-2af7c645ba12" />

**Comment by spawnrider** [comment]
It's ok for me.
You effectively need to add the @analogjs/vite-plugin-angular component in your package.json else the SCSS will not be processed.
