### ISSUE TITLE
Getting started not working with Node 16. 

### ISSUE THREAD

**Issue by JeanMeche** [analogjs/analog#527]
### Please provide the environment you discovered this bug in.

See the stackblitz example : https://stackblitz.com/github/analogjs/analog/tree/main/packages/create-analog/template-angular-v16 

### Which area/package is the issue in?

create-analog

### Description

I created a new project using the getting started : 

On Node 16.19.1 : 
* `npm create analog@latest` then installing the deps with `npm install`
* started the project with `npm run dev`. 
* open the page on the browser: 

I'm getting : 

```
5:02:10 PM [vite] Error when evaluating SSR module /node_modules/@angular/core/fesm2022/core.mjs: failed to import "rxjs"
|- TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at ZoneAwarePromise.then (<anonymous>)
    at node:internal/per_context/primordials:440:35
    at new Promise (<anonymous>)
    at new SafePromise (node:internal/per_context/primordials:408:29)
    at node:internal/per_context/primordials:440:9
    at Array.map (<anonymous>)
    at arrayToSafePromiseIterable (node:internal/per_context/primordials:437:5)
    at node:internal/per_context/primordials:453:21
    at new Promise (<anonymous>)
    at primordials.SafePromiseAll (node:internal/per_context/primordials:452:3)

5:02:10 PM [vite] Error when evaluating SSR module ~analog/entry-server: failed to import "/node_modules/@angular/core/fesm2022/core.mjs"
|- TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at ZoneAwarePromise.then (<anonymous>)
    at node:internal/per_context/primordials:440:35
    at new Promise (<anonymous>)
    at new SafePromise (node:internal/per_context/primordials:408:29)
    at node:internal/per_context/primordials:440:9
    at Array.map (<anonymous>)
    at arrayToSafePromiseIterable (node:internal/per_context/primordials:437:5)
    at node:internal/per_context/primordials:453:21
    at new Promise (<anonymous>)
    at primordials.SafePromiseAll (node:internal/per_context/primordials:452:3)
```

This doesn't happen with the same deps (no reinstall) on node 18.15.0.

**Comment by brandonroberts** [comment]
Node version 18.13.0 and up is recommended due to fixes landing in Node and Angular around patching Promises.

16.17.0 has worked fine for me previously

https://github.com/analogjs/analog/issues/203

**Comment by JeanMeche** [comment]
I can confirm that `16.17.0` works fine but `16.18.1` & `16.19.1` are broken.

**Comment by brandonroberts** [comment]
Cool, filed an issue to update the `engines` in `create-analog`

https://github.com/analogjs/analog/issues/532

**Comment by brandonroberts** [comment]
Fixed by https://github.com/analogjs/analog/pull/533

**Comment by norato** [comment]
@brandonroberts  for 0.2.0-beta.25 the error persists on node v16.20.0

**Comment by brandonroberts** [comment]
@norato yes, I've noticed that also. The recommended versions are in the previous comment
